### ISSUE TITLE
Adapter ontology definition

### ISSUE THREAD

**Issue by MilanJovic92** [vicinityh2020/vicinity-agent#2]
Hi, as we have discussed in the conference, we would like an example of the use of vicinity ontology. Can you provide us with a link? Thank you

**Comment by mkoutli** [comment]
Hello, Adapter needs to provide to agent a Thing description as presented [here](https://github.com/vicinityh2020/vicinity-agent/blob/master/docs/ADAPTER.md). An example of a Thing Description can be found [here](https://github.com/vicinityh2020/vicinity-agent/blob/master/docs/TDExamples.md). The mandatory fields that concern Ontology are: the device "type" and the interaction pattern (e.g. property) "monitors" values. For these values you will need to take a look at the Ontology which can be found [here](http://iot.linkeddata.es/def/adapters/index-en.html). Also this video tutorial guide has a video dedicated to Thing Description and the connection with Ontology [link](https://vicinity2020.eu/vicinity/content/quick-start-guide)
